USE deadlocktestdb;

INSERT INTO Table1 VALUES ('TESTVAL1', 'TESTVAL2');
BEGIN TRANSACTION;
WAITFOR DELAY '00:00:05'
UPDATE Table1 SET name = 'CHANGEDVAL1', somestr = 'CHANGEDVAL2' WHERE name = 'TESTVAL1' AND somestr = 'TESTVAL2';
COMMIT TRANSACTION;

DELETE FROM Table1 WHERE name = 'CHANGEDVAL1' AND somestr = 'CHANGEDVAL2'